language: node_js

os:
  - linux
  - osx

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - gatsby

cache:
  directories:
    - node_modules

before_script:
  - "npm i -g gatsby-cli"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  - "yarn"

script:
  - yarn install
  - yarn run lint
  - gatsby build